@name dev

GET {{baseUrl}}{{apiPrefix}}/chargepoints/1
Accept: application/json

###
# @name crete chargepoint
POST {{baseUrl}}{{apiPrefix}}/chargepoints
Content-Type: application/json
Accept: application/json

{
  "name": "Charge Point 1",
  "status": "available",
  "code": "CP001"
}
